//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountProfile()
        {
            this.LoneLedgers = new HashSet<LoneLedger>();
        }
    
        public string AccNo { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string NIC { get; set; }
        public string AccOpenDate { get; set; }
        public string Bank { get; set; }
        public string DOB { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> ReferancePersonID { get; set; }
        public string MemberID { get; set; }
    
        public virtual AccRefPerson AccRefPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoneLedger> LoneLedgers { get; set; }
    }
}
