//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanSummary()
        {
            this.LoneLedgers = new HashSet<LoneLedger>();
        }
    
        public int LoanSummaryID { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> PaidInterestAmount { get; set; }
        public Nullable<double> InterestBalance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoneLedger> LoneLedgers { get; set; }
    }
}
