//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESamurdhiEntities : DbContext
    {
        public ESamurdhiEntities()
            : base("name=ESamurdhiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountProfile> AccountProfiles { get; set; }
        public virtual DbSet<AccRefPerson> AccRefPersons { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Guarantor> Guarantors { get; set; }
        public virtual DbSet<LoanSummary> LoanSummaries { get; set; }
        public virtual DbSet<LoanType> LoanTypes { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<LoneLedger> LoneLedgers { get; set; }
    }
}
