//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoneLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoneLedger()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int LoanNo { get; set; }
        public string AccNo { get; set; }
        public Nullable<int> GroupAccNo { get; set; }
        public string MemberID { get; set; }
        public double LoanAmount { get; set; }
        public int GuarantorsID { get; set; }
        public string Reason { get; set; }
        public Nullable<int> LoanTypeID { get; set; }
        public string ReleasedDate { get; set; }
        public Nullable<int> AreaID { get; set; }
        public bool IsFullPaid { get; set; }
        public Nullable<int> LoanSummaryID { get; set; }
    
        public virtual AccountProfile AccountProfile { get; set; }
        public virtual Area Area { get; set; }
        public virtual Guarantor Guarantor { get; set; }
        public virtual LoanSummary LoanSummary { get; set; }
        public virtual LoanType LoanType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
