//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int LoanNo { get; set; }
        public string Month { get; set; }
        public double PaidAmount { get; set; }
        public string PaidDate { get; set; }
        public int TransactionNo { get; set; }
    
        public virtual LoneLedger LoneLedger { get; set; }
    }
}
